name: 'Run Tests'
description: 'Run project tests with coverage'

inputs:
  test-path:
    description: 'Path to test directory or file'
    required: false
    default: 'tests/'
  cov-path:
    description: 'Path to measure coverage for'
    required: false
    default: 'src'
  cov-append:
    description: 'Whether to append to coverage file'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install package and test dependencies
      shell: bash
      run: |
        set -e
        # Ensure pip is up to date
        python -m pip install --upgrade pip
        # Install package in development mode with test dependencies
        python -m pip install -e ".[test]"
        # Verify pytest is installed
        python -m pytest --version

    - name: Run tests with coverage
      shell: bash
      run: |
        set -e
        # Set PYTHONPATH to include the src directory
        export PYTHONPATH=/home/runner/work/rag/rag/src:$PYTHONPATH

        # Build coverage arguments
        cov_args=(
          "--cov=${{ inputs.cov-path }}"
          "--cov-report=term-missing"
          "--cov-report=xml"
          "-v"
        )

        if [[ "${{ inputs.cov-append }}" == "true" ]]; then
          cov_args+=( "--cov-append" )
        fi

        # Run pytest with the specified test path and coverage arguments
        python -m pytest ${{ inputs.test-path }} "${cov_args[@]}"

    - name: Upload coverage to Codecov
      if: github.event_name != 'pull_request' && inputs.cov-append == 'false'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
