name: Docker

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./container/Dockerfile
          load: true
          tags: rag:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test CLI startup
        run: |
          docker run --rm rag:test rag --version || docker run --rm rag:test rag --help

      - name: Test module import
        run: |
          docker run --rm rag:test python -c "import rag; print('Import successful')"

      - name: Clean up Docker cache
        run: |
          docker system prune -af || true
          docker builder prune -af || true
