name: Docker

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./container/Dockerfile
          load: true
          tags: rag:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify image imports
        run: |
          docker run --rm rag:test python -c "import src.rag.__main__; import src.rag.rag_engine; import src.rag.config; import src.rag.tools; import src.rag.data_fetcher; print('All imports successful')"

      - name: Display CLI help safely
        run: |
          echo -e "exit" | docker run -i --rm rag:test rag --help

      - name: Display TUI safely
        run: |
          echo -e "exit" | docker run -i --rm rag:test python -c "from src.rag.ui.tui import run_tui; run_tui()"

      - name: Clean up
        run: |
          docker system prune -f || true
          docker image prune -f || true
          docker volume prune -f || true
          docker builder prune -f || true
